CFLAGS = \
	$(2) \
	-nostartfiles \
	-I $(ROOTDIR)/riscv-test-env/ \
	-I $(ROOTDIR)/riscv-test-env/p/ \
	-I $(TARGETDIR)/$(RISCV_TARGET)/ \
	-T $(SHITVDIR)/sw/link.ld

COMPILE_TARGET = \
	$(RISCV_PREFIX)gcc \
		$(CFLAGS) \
		-o $(work_dir_isa)/$$@ \
		$$< \
	&& $(RISCV_PREFIX)objcopy \
		-O verilog \
		$(work_dir_isa)/$$@ \
		$(work_dir_isa)/$$@.hex

RUN_TARGET = \
	make -C $(SHITVDIR)/sim \
		runhex \
		CUSTOM_HEX=$(work_dir_isa)/$<.hex \
		> $(work_dir_isa)/$@
